### ISSUE TITLE
Inconsistent cropping dimension for the volume 'PDM741426OS.img'

### ISSUE THREAD

**Issue by glemaitre** [khaledalsaih/oct-1#3]
Got the following error:
`The dimension heights dimension are inconsistent to make a cropping.`

It means that we try to crop outside of the image.
@khaledalsaih you have to check what is happening for this specific case.

**Comment by khaledalsaih** [comment]
Solve in commit #76a75ea66d8bc58fde5e07bc3397e3cdb57240c8
